#!/usr/bin/env sh

VERSION=${1:-0.0.0}
GIT_COMMIT=$(git rev-parse HEAD)
COMMIT=${GIT_COMMIT:-<Not built from git>}
BUILT_AT=$(date +%FT%T%z)
BUILT_BY=${USER}
BUILT_ON=$(hostname)

go build -o ./consul-zeroconf \
  -trimpath \
  -ldflags "-s -w -X 'main.appVersion=${VERSION}' -X 'main.appCommit=${COMMIT}' -X 'main.appBuiltAt=${BUILT_AT}' -X 'main.appBuiltBy=${BUILT_BY}' -X 'main.appBuiltOn=${BUILT_ON}'" \
  .
